################################################################################
# 11_supplementary_figures.R
#
# Supplementary figures
################################################################################

source("R/00_setup.R")


################################################################################
# FIGURE S1
# Effort-standardised temporal patterns
#
# Seven localities monitored in all three monitoring cycles.
#
# Coloured trajectories:
# locality-specific median estimates across 1,000 rarefaction iterations.
#
# Black points and lines:
# median cycle-level mean across 1,000 rarefaction iterations.
#
# Error bars:
# 2.5-97.5% rarefaction intervals for the cycle-level mean.
################################################################################


################################################################################
# S1.1. Parameters
################################################################################

cycle_levels_s1 <- c(
  "2022/2023",
  "2023/2024",
  "2024/2025"
)


################################################################################
# S1.2. Read outputs generated by script 08
################################################################################

temporal_locality <- read_csv(
  "outputs/reviewer8_temporal_rarefied_metrics.csv",
  show_col_types = FALSE
) |>
  mutate(
    monitoring_cycle = factor(
      monitoring_cycle,
      levels = cycle_levels_s1,
      ordered = TRUE
    ),
    
    localidade = factor(
      localidade
    )
  )


sensitivity_descriptive_summary <- read_csv(
  "outputs/sensitivity_descriptive_summary.csv",
  show_col_types = FALSE
)


temporal_summary <- sensitivity_descriptive_summary |>
  filter(
    analysis == "Temporal"
  ) |>
  transmute(
    monitoring_cycle = factor(
      category,
      levels = cycle_levels_s1,
      ordered = TRUE
    ),
    
    dpue =
      detection_metric,
    
    dpue_lower =
      detection_lower,
    
    dpue_upper =
      detection_upper,
    
    rai_w =
      abundance_metric,
    
    raiw_lower =
      abundance_lower,
    
    raiw_upper =
      abundance_upper
  )


################################################################################
# S1.3. Checks
################################################################################

stopifnot(
  n_distinct(
    temporal_locality$localidade
  ) == 7,
  
  n_distinct(
    temporal_locality$monitoring_cycle
  ) == 3,
  
  nrow(
    temporal_locality
  ) == 21,
  
  nrow(
    temporal_summary
  ) == 3
)


figure_s1_design_check <- temporal_locality |>
  count(
    localidade,
    monitoring_cycle,
    name = "n"
  )


stopifnot(
  all(
    figure_s1_design_check$n == 1
  )
)


cat(
  "\nFigure S1 locality-level values\n"
)

print(
  temporal_locality |>
    select(
      localidade,
      monitoring_cycle,
      dpue,
      rai_w
    ) |>
    arrange(
      localidade,
      monitoring_cycle
    ),
  n = Inf
)


cat(
  "\nFigure S1 cycle-level summary\n"
)

print(
  temporal_summary,
  n = Inf
)


################################################################################
# S1.4. Panel A - DPUE
################################################################################

plot_s1a <- ggplot() +
  
  geom_line(
    data = temporal_locality,
    aes(
      x = monitoring_cycle,
      y = dpue,
      group = localidade,
      colour = localidade
    ),
    linewidth = 0.7,
    alpha = 0.9
  ) +
  
  geom_point(
    data = temporal_locality,
    aes(
      x = monitoring_cycle,
      y = dpue,
      colour = localidade
    ),
    size = 2
  ) +
  
  geom_errorbar(
    data = temporal_summary,
    aes(
      x = monitoring_cycle,
      ymin = dpue_lower,
      ymax = dpue_upper
    ),
    width = 0.08,
    linewidth = 0.9,
    colour = "black"
  ) +
  
  geom_line(
    data = temporal_summary,
    aes(
      x = monitoring_cycle,
      y = dpue,
      group = 1
    ),
    linewidth = 1.2,
    colour = "black"
  ) +
  
  geom_point(
    data = temporal_summary,
    aes(
      x = monitoring_cycle,
      y = dpue
    ),
    size = 3,
    colour = "black"
  ) +
  
  scale_x_discrete(
    drop = FALSE
  ) +
  
  labs(
    x = "Monitoring cycle",
    y = "DPUE",
    colour = "Locality"
  ) +
  
  theme_bw(
    base_size = 13
  ) +
  
  theme(
    panel.grid.minor =
      element_blank(),
    
    legend.position =
      "right"
  )


################################################################################
# S1.5. Panel B - RAI-W
################################################################################

plot_s1b <- ggplot() +
  
  geom_line(
    data = temporal_locality,
    aes(
      x = monitoring_cycle,
      y = rai_w,
      group = localidade,
      colour = localidade
    ),
    linewidth = 0.7,
    alpha = 0.9
  ) +
  
  geom_point(
    data = temporal_locality,
    aes(
      x = monitoring_cycle,
      y = rai_w,
      colour = localidade
    ),
    size = 2
  ) +
  
  geom_errorbar(
    data = temporal_summary,
    aes(
      x = monitoring_cycle,
      ymin = raiw_lower,
      ymax = raiw_upper
    ),
    width = 0.08,
    linewidth = 0.9,
    colour = "black"
  ) +
  
  geom_line(
    data = temporal_summary,
    aes(
      x = monitoring_cycle,
      y = rai_w,
      group = 1
    ),
    linewidth = 1.2,
    colour = "black"
  ) +
  
  geom_point(
    data = temporal_summary,
    aes(
      x = monitoring_cycle,
      y = rai_w
    ),
    size = 3,
    colour = "black"
  ) +
  
  scale_x_discrete(
    drop = FALSE
  ) +
  
  labs(
    x = "Monitoring cycle",
    y = "RAI-W",
    colour = "Locality"
  ) +
  
  theme_bw(
    base_size = 13
  ) +
  
  theme(
    panel.grid.minor =
      element_blank(),
    
    legend.position =
      "right"
  )


################################################################################
# S1.6. Combine Figure S1
################################################################################

figure_s1 <- (
  plot_s1a +
    plot_s1b
) +
  plot_layout(
    ncol = 2,
    guides = "collect"
  ) +
  plot_annotation(
    tag_levels = "A"
  ) &
  
  theme(
    legend.position =
      "right",
    
    legend.title =
      element_text(
        face = "bold"
      ),
    
    plot.tag =
      element_text(
        face = "bold",
        size = 14
      )
  )


figure_s1


################################################################################
# S1.7. Export Figure S1
################################################################################

ggsave(
  filename =
    "figs/Figure_S1_temporal_effort_standardised.png",
  
  plot =
    figure_s1,
  
  width = 14,
  height = 7,
  units = "in",
  dpi = 300
)


################################################################################
# S1.8. Export Figure S1 source tables
################################################################################

write_csv(
  temporal_locality,
  "outputs/Figure_S1_temporal_locality_trajectories.csv"
)

write_csv(
  temporal_summary,
  "outputs/Figure_S1_temporal_summary.csv"
)


################################################################################
# end Figure S1
################################################################################